name: Deploy to Cloudflare Dxx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Cloudflare Pages Deployment
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Bun
        run: npm install --global bun

      - name: Install Wrangler
        run: npm install --save-dev wrangler@4

      - name: Build Project
        run: bun run build  # Ensure this creates the `dist/` folder

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy ./dist --project-name cf-image-hosting
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
